// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6f824240-504c-4e4f-b56c-5dbf1d2fb475";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSampleTimeChange();
void onAirQualityChange();

float ccs811_CO2;
float ccs811_VOC;
float mq135_ppm;
float sample_time;
bool air_quality;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ccs811_CO2, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(ccs811_VOC, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(mq135_ppm, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sample_time, READWRITE, ON_CHANGE, onSampleTimeChange);
  ArduinoCloud.addProperty(air_quality, READWRITE, ON_CHANGE, onAirQualityChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
